/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as PublicBoardBoardIdRouteImport } from './routes/public-board.$boardId'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedInvitationsRouteImport } from './routes/_layout/_authenticated/invitations'
import { Route as LayoutAuthenticatedOnboardingRouteImport } from './routes/_layout/_authenticated/onboarding'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as InvitationAcceptInviteIdRouteImport } from './routes/invitation/accept.$inviteId'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardInvitationsRouteImport } from './routes/_layout/_authenticated/dashboard/invitations'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId'
import { Route as LayoutAuthenticatedDashboardOrganizationCreateRouteImport } from './routes/_layout/_authenticated/dashboard/organization/create'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardSettingsBoardsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/boards'
import { Route as LayoutAuthenticatedDashboardSettingsConnectionsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/connections'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/index'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/members'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/search'
import { Route as LayoutAuthenticatedDashboardSettingsAccountConnectionsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/connections'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardSettingsAccountGithubRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/github'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization/connections'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization/general'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationGithubRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization/github'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationLabelsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization/labels'
import { Route as LayoutAuthenticatedDashboardSettingsOrganizationRolesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/organization/roles'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/index'
import { Route as LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/boards/$boardId/general'
import { Route as LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/boards/$boardId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/boards/$boardId/visibility'
import { Route as LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/boards/$boardId/workflow'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/index'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/backlog'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/board'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/gantt'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/index'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/code'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/packages'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/releases'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/task/$taskId_'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
import { Route as LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRouteImport } from './routes/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBoardBoardIdRoute = PublicBoardBoardIdRouteImport.update({
  id: '/public-board/$boardId',
  path: '/public-board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedInvitationsRoute =
  LayoutAuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOnboardingRoute =
  LayoutAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const InvitationAcceptInviteIdRoute =
  InvitationAcceptInviteIdRouteImport.update({
    id: '/invitation/accept/$inviteId',
    path: '/invitation/accept/$inviteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardInvitationsRoute =
  LayoutAuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteImport.update({
    id: '/organization/$organizationId',
    path: '/organization/$organizationId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationCreateRoute =
  LayoutAuthenticatedDashboardOrganizationCreateRouteImport.update({
    id: '/organization/create',
    path: '/organization/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsBoardsRoute =
  LayoutAuthenticatedDashboardSettingsBoardsRouteImport.update({
    id: '/boards',
    path: '/boards',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsConnectionsRoute =
  LayoutAuthenticatedDashboardSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsOrganizationRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRouteImport.update(
    {
      id: '/members',
      path: '/members',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRouteImport.update(
    {
      id: '/search',
      path: '/search',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute =
  LayoutAuthenticatedDashboardSettingsAccountConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountGithubRoute =
  LayoutAuthenticatedDashboardSettingsAccountGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRouteImport.update(
    {
      id: '/connections',
      path: '/connections',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardSettingsOrganizationRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsOrganizationRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsOrganizationRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsOrganizationRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute =
  LayoutAuthenticatedDashboardSettingsOrganizationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsOrganizationRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRouteImport.update(
    {
      id: '/repo/',
      path: '/repo/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRouteImport.update({
    id: '/$boardId/general',
    path: '/$boardId/general',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsBoardsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRouteImport.update(
    {
      id: '/$boardId/integrations',
      path: '/$boardId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsBoardsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute =
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRouteImport.update(
    {
      id: '/$boardId/visibility',
      path: '/$boardId/visibility',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsBoardsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRouteImport.update({
    id: '/$boardId/workflow',
    path: '/$boardId/workflow',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsBoardsRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRouteImport.update(
    {
      id: '/board/$boardId/',
      path: '/board/$boardId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRouteImport.update(
    {
      id: '/board/$boardId/backlog',
      path: '/board/$boardId/backlog',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRouteImport.update(
    {
      id: '/board/$boardId/board',
      path: '/board/$boardId/board',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRouteImport.update(
    {
      id: '/board/$boardId/gantt',
      path: '/board/$boardId/gantt',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRouteImport.update(
    {
      id: '/repo/$repoId/',
      path: '/repo/$repoId/',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRouteImport.update(
    {
      id: '/repo/$repoId/code',
      path: '/repo/$repoId/code',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteImport.update(
    {
      id: '/repo/$repoId/issues',
      path: '/repo/$repoId/issues',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRouteImport.update(
    {
      id: '/repo/$repoId/packages',
      path: '/repo/$repoId/packages',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteImport.update(
    {
      id: '/repo/$repoId/pulls',
      path: '/repo/$repoId/pulls',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRouteImport.update(
    {
      id: '/repo/$repoId/releases',
      path: '/repo/$repoId/releases',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRouteImport.update(
    {
      id: '/board/$boardId/task/$taskId_',
      path: '/board/$boardId/task/$taskId',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRouteImport.update(
    {
      id: '/$number',
      path: '/$number',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRouteImport.update(
    {
      id: '/$number',
      path: '/$number',
      getParentRoute: () =>
        LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-board/$boardId': typeof PublicBoardBoardIdRoute
  '/device/': typeof DeviceIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/organization/$organizationId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteWithChildren
  '/dashboard/organization/create': typeof LayoutAuthenticatedDashboardOrganizationCreateRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/boards': typeof LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren
  '/dashboard/settings/connections': typeof LayoutAuthenticatedDashboardSettingsConnectionsRoute
  '/dashboard/settings/organization': typeof LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren
  '/dashboard/organization/$organizationId/members': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute
  '/dashboard/organization/$organizationId/search': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute
  '/dashboard/settings/account/connections': typeof LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/github': typeof LayoutAuthenticatedDashboardSettingsAccountGithubRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/organization/connections': typeof LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute
  '/dashboard/settings/organization/general': typeof LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute
  '/dashboard/settings/organization/github': typeof LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute
  '/dashboard/settings/organization/labels': typeof LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute
  '/dashboard/settings/organization/roles': typeof LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute
  '/dashboard/organization/$organizationId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute
  '/dashboard/settings/boards/$boardId/general': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute
  '/dashboard/settings/boards/$boardId/integrations': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute
  '/dashboard/settings/boards/$boardId/visibility': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute
  '/dashboard/settings/boards/$boardId/workflow': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute
  '/dashboard/organization/$organizationId/repo/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute
  '/dashboard/organization/$organizationId/board/$boardId/backlog': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute
  '/dashboard/organization/$organizationId/board/$boardId/board': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute
  '/dashboard/organization/$organizationId/board/$boardId/gantt': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute
  '/dashboard/organization/$organizationId/repo/$repoId/code': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute
  '/dashboard/organization/$organizationId/repo/$repoId/issues': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren
  '/dashboard/organization/$organizationId/repo/$repoId/packages': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute
  '/dashboard/organization/$organizationId/repo/$repoId/pulls': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren
  '/dashboard/organization/$organizationId/repo/$repoId/releases': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute
  '/dashboard/organization/$organizationId/board/$boardId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute
  '/dashboard/organization/$organizationId/repo/$repoId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute
  '/dashboard/organization/$organizationId/board/$boardId/task/$taskId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute
  '/dashboard/organization/$organizationId/repo/$repoId/issues/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute
  '/dashboard/organization/$organizationId/repo/$repoId/pulls/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-board/$boardId': typeof PublicBoardBoardIdRoute
  '/device': typeof DeviceIndexRoute
  '/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/organization/create': typeof LayoutAuthenticatedDashboardOrganizationCreateRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/boards': typeof LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren
  '/dashboard/settings/connections': typeof LayoutAuthenticatedDashboardSettingsConnectionsRoute
  '/dashboard/settings/organization': typeof LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren
  '/dashboard/organization/$organizationId/members': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute
  '/dashboard/organization/$organizationId/search': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute
  '/dashboard/settings/account/connections': typeof LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/github': typeof LayoutAuthenticatedDashboardSettingsAccountGithubRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/organization/connections': typeof LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute
  '/dashboard/settings/organization/general': typeof LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute
  '/dashboard/settings/organization/github': typeof LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute
  '/dashboard/settings/organization/labels': typeof LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute
  '/dashboard/settings/organization/roles': typeof LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute
  '/dashboard/organization/$organizationId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute
  '/dashboard/settings/boards/$boardId/general': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute
  '/dashboard/settings/boards/$boardId/integrations': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute
  '/dashboard/settings/boards/$boardId/visibility': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute
  '/dashboard/settings/boards/$boardId/workflow': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute
  '/dashboard/organization/$organizationId/repo': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute
  '/dashboard/organization/$organizationId/board/$boardId/backlog': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute
  '/dashboard/organization/$organizationId/board/$boardId/board': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute
  '/dashboard/organization/$organizationId/board/$boardId/gantt': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute
  '/dashboard/organization/$organizationId/repo/$repoId/code': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute
  '/dashboard/organization/$organizationId/repo/$repoId/issues': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren
  '/dashboard/organization/$organizationId/repo/$repoId/packages': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute
  '/dashboard/organization/$organizationId/repo/$repoId/pulls': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren
  '/dashboard/organization/$organizationId/repo/$repoId/releases': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute
  '/dashboard/organization/$organizationId/board/$boardId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute
  '/dashboard/organization/$organizationId/repo/$repoId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute
  '/dashboard/organization/$organizationId/board/$boardId/task/$taskId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute
  '/dashboard/organization/$organizationId/repo/$repoId/issues/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute
  '/dashboard/organization/$organizationId/repo/$repoId/pulls/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-board/$boardId': typeof PublicBoardBoardIdRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/invitations': typeof LayoutAuthenticatedInvitationsRoute
  '/_layout/_authenticated/onboarding': typeof LayoutAuthenticatedOnboardingRoute
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/invitation/accept/$inviteId': typeof InvitationAcceptInviteIdRoute
  '/_layout/_authenticated/dashboard/invitations': typeof LayoutAuthenticatedDashboardInvitationsRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteWithChildren
  '/_layout/_authenticated/dashboard/organization/create': typeof LayoutAuthenticatedDashboardOrganizationCreateRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/boards': typeof LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/connections': typeof LayoutAuthenticatedDashboardSettingsConnectionsRoute
  '/_layout/_authenticated/dashboard/settings/organization': typeof LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren
  '/_layout/_authenticated/dashboard/organization/$organizationId/members': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/search': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute
  '/_layout/_authenticated/dashboard/settings/account/connections': typeof LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/github': typeof LayoutAuthenticatedDashboardSettingsAccountGithubRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/organization/connections': typeof LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute
  '/_layout/_authenticated/dashboard/settings/organization/general': typeof LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute
  '/_layout/_authenticated/dashboard/settings/organization/github': typeof LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute
  '/_layout/_authenticated/dashboard/settings/organization/labels': typeof LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute
  '/_layout/_authenticated/dashboard/settings/organization/roles': typeof LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/boards/$boardId/general': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/boards/$boardId/integrations': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/boards/$boardId/visibility': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute
  '/_layout/_authenticated/dashboard/settings/boards/$boardId/workflow': typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/backlog': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/board': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/gantt': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/code': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/packages': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/releases': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/task/$taskId_': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute
  '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls/$number': typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-board/$boardId'
    | '/device/'
    | '/dashboard'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/organization/$organizationId'
    | '/dashboard/organization/create'
    | '/dashboard/settings/account'
    | '/dashboard/settings/boards'
    | '/dashboard/settings/connections'
    | '/dashboard/settings/organization'
    | '/dashboard/organization/$organizationId/members'
    | '/dashboard/organization/$organizationId/search'
    | '/dashboard/settings/account/connections'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/github'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/organization/connections'
    | '/dashboard/settings/organization/general'
    | '/dashboard/settings/organization/github'
    | '/dashboard/settings/organization/labels'
    | '/dashboard/settings/organization/roles'
    | '/dashboard/organization/$organizationId/'
    | '/dashboard/settings/boards/$boardId/general'
    | '/dashboard/settings/boards/$boardId/integrations'
    | '/dashboard/settings/boards/$boardId/visibility'
    | '/dashboard/settings/boards/$boardId/workflow'
    | '/dashboard/organization/$organizationId/repo/'
    | '/dashboard/organization/$organizationId/board/$boardId/backlog'
    | '/dashboard/organization/$organizationId/board/$boardId/board'
    | '/dashboard/organization/$organizationId/board/$boardId/gantt'
    | '/dashboard/organization/$organizationId/repo/$repoId/code'
    | '/dashboard/organization/$organizationId/repo/$repoId/issues'
    | '/dashboard/organization/$organizationId/repo/$repoId/packages'
    | '/dashboard/organization/$organizationId/repo/$repoId/pulls'
    | '/dashboard/organization/$organizationId/repo/$repoId/releases'
    | '/dashboard/organization/$organizationId/board/$boardId/'
    | '/dashboard/organization/$organizationId/repo/$repoId/'
    | '/dashboard/organization/$organizationId/board/$boardId/task/$taskId'
    | '/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
    | '/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-board/$boardId'
    | '/device'
    | '/invitations'
    | '/onboarding'
    | '/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/organization/create'
    | '/dashboard/settings/account'
    | '/dashboard/settings/boards'
    | '/dashboard/settings/connections'
    | '/dashboard/settings/organization'
    | '/dashboard/organization/$organizationId/members'
    | '/dashboard/organization/$organizationId/search'
    | '/dashboard/settings/account/connections'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/github'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/organization/connections'
    | '/dashboard/settings/organization/general'
    | '/dashboard/settings/organization/github'
    | '/dashboard/settings/organization/labels'
    | '/dashboard/settings/organization/roles'
    | '/dashboard/organization/$organizationId'
    | '/dashboard/settings/boards/$boardId/general'
    | '/dashboard/settings/boards/$boardId/integrations'
    | '/dashboard/settings/boards/$boardId/visibility'
    | '/dashboard/settings/boards/$boardId/workflow'
    | '/dashboard/organization/$organizationId/repo'
    | '/dashboard/organization/$organizationId/board/$boardId/backlog'
    | '/dashboard/organization/$organizationId/board/$boardId/board'
    | '/dashboard/organization/$organizationId/board/$boardId/gantt'
    | '/dashboard/organization/$organizationId/repo/$repoId/code'
    | '/dashboard/organization/$organizationId/repo/$repoId/issues'
    | '/dashboard/organization/$organizationId/repo/$repoId/packages'
    | '/dashboard/organization/$organizationId/repo/$repoId/pulls'
    | '/dashboard/organization/$organizationId/repo/$repoId/releases'
    | '/dashboard/organization/$organizationId/board/$boardId'
    | '/dashboard/organization/$organizationId/repo/$repoId'
    | '/dashboard/organization/$organizationId/board/$boardId/task/$taskId'
    | '/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
    | '/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-board/$boardId'
    | '/device/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/invitations'
    | '/_layout/_authenticated/onboarding'
    | '/_layout/_authenticated/profile-setup'
    | '/invitation/accept/$inviteId'
    | '/_layout/_authenticated/dashboard/invitations'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/organization/$organizationId'
    | '/_layout/_authenticated/dashboard/organization/create'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/boards'
    | '/_layout/_authenticated/dashboard/settings/connections'
    | '/_layout/_authenticated/dashboard/settings/organization'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/members'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/search'
    | '/_layout/_authenticated/dashboard/settings/account/connections'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/github'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/organization/connections'
    | '/_layout/_authenticated/dashboard/settings/organization/general'
    | '/_layout/_authenticated/dashboard/settings/organization/github'
    | '/_layout/_authenticated/dashboard/settings/organization/labels'
    | '/_layout/_authenticated/dashboard/settings/organization/roles'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/'
    | '/_layout/_authenticated/dashboard/settings/boards/$boardId/general'
    | '/_layout/_authenticated/dashboard/settings/boards/$boardId/integrations'
    | '/_layout/_authenticated/dashboard/settings/boards/$boardId/visibility'
    | '/_layout/_authenticated/dashboard/settings/boards/$boardId/workflow'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/backlog'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/board'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/gantt'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/code'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/packages'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/releases'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/task/$taskId_'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
    | '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  PublicBoardBoardIdRoute: typeof PublicBoardBoardIdRoute
  InvitationAcceptInviteIdRoute: typeof InvitationAcceptInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-board/$boardId': {
      id: '/public-board/$boardId'
      path: '/public-board/$boardId'
      fullPath: '/public-board/$boardId'
      preLoaderRoute: typeof PublicBoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/invitations': {
      id: '/_layout/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/onboarding': {
      id: '/_layout/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutAuthenticatedOnboardingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/invitation/accept/$inviteId': {
      id: '/invitation/accept/$inviteId'
      path: '/invitation/accept/$inviteId'
      fullPath: '/invitation/accept/$inviteId'
      preLoaderRoute: typeof InvitationAcceptInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/invitations': {
      id: '/_layout/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId'
      path: '/organization/$organizationId'
      fullPath: '/dashboard/organization/$organizationId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/organization/create': {
      id: '/_layout/_authenticated/dashboard/organization/create'
      path: '/organization/create'
      fullPath: '/dashboard/organization/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/boards': {
      id: '/_layout/_authenticated/dashboard/settings/boards'
      path: '/boards'
      fullPath: '/dashboard/settings/boards'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/connections': {
      id: '/_layout/_authenticated/dashboard/settings/connections'
      path: '/connections'
      fullPath: '/dashboard/settings/connections'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsConnectionsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization': {
      id: '/_layout/_authenticated/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/'
      path: '/'
      fullPath: '/dashboard/organization/$organizationId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/members': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/members'
      path: '/members'
      fullPath: '/dashboard/organization/$organizationId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/search': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/search'
      path: '/search'
      fullPath: '/dashboard/organization/$organizationId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/connections': {
      id: '/_layout/_authenticated/dashboard/settings/account/connections'
      path: '/connections'
      fullPath: '/dashboard/settings/account/connections'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountConnectionsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/github': {
      id: '/_layout/_authenticated/dashboard/settings/account/github'
      path: '/github'
      fullPath: '/dashboard/settings/account/github'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountGithubRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization/connections': {
      id: '/_layout/_authenticated/dashboard/settings/organization/connections'
      path: '/connections'
      fullPath: '/dashboard/settings/organization/connections'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization/general': {
      id: '/_layout/_authenticated/dashboard/settings/organization/general'
      path: '/general'
      fullPath: '/dashboard/settings/organization/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization/github': {
      id: '/_layout/_authenticated/dashboard/settings/organization/github'
      path: '/github'
      fullPath: '/dashboard/settings/organization/github'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationGithubRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization/labels': {
      id: '/_layout/_authenticated/dashboard/settings/organization/labels'
      path: '/labels'
      fullPath: '/dashboard/settings/organization/labels'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationLabelsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRoute
    }
    '/_layout/_authenticated/dashboard/settings/organization/roles': {
      id: '/_layout/_authenticated/dashboard/settings/organization/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/organization/roles'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRolesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/'
      path: '/repo'
      fullPath: '/dashboard/organization/$organizationId/repo/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/boards/$boardId/general': {
      id: '/_layout/_authenticated/dashboard/settings/boards/$boardId/general'
      path: '/$boardId/general'
      fullPath: '/dashboard/settings/boards/$boardId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRoute
    }
    '/_layout/_authenticated/dashboard/settings/boards/$boardId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/boards/$boardId/integrations'
      path: '/$boardId/integrations'
      fullPath: '/dashboard/settings/boards/$boardId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRoute
    }
    '/_layout/_authenticated/dashboard/settings/boards/$boardId/visibility': {
      id: '/_layout/_authenticated/dashboard/settings/boards/$boardId/visibility'
      path: '/$boardId/visibility'
      fullPath: '/dashboard/settings/boards/$boardId/visibility'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRoute
    }
    '/_layout/_authenticated/dashboard/settings/boards/$boardId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/boards/$boardId/workflow'
      path: '/$boardId/workflow'
      fullPath: '/dashboard/settings/boards/$boardId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/'
      path: '/board/$boardId'
      fullPath: '/dashboard/organization/$organizationId/board/$boardId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/backlog': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/backlog'
      path: '/board/$boardId/backlog'
      fullPath: '/dashboard/organization/$organizationId/board/$boardId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/board': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/board'
      path: '/board/$boardId/board'
      fullPath: '/dashboard/organization/$organizationId/board/$boardId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/gantt': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/gantt'
      path: '/board/$boardId/gantt'
      fullPath: '/dashboard/organization/$organizationId/board/$boardId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/'
      path: '/repo/$repoId'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/code': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/code'
      path: '/repo/$repoId/code'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/code'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues'
      path: '/repo/$repoId/issues'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/issues'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/packages': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/packages'
      path: '/repo/$repoId/packages'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/packages'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls'
      path: '/repo/$repoId/pulls'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/pulls'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/releases': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/releases'
      path: '/repo/$repoId/releases'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/releases'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/board/$boardId/task/$taskId_'
      path: '/board/$boardId/task/$taskId'
      fullPath: '/dashboard/organization/$organizationId/board/$boardId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues/$number': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
      path: '/$number'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/issues/$number'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute
    }
    '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls/$number': {
      id: '/_layout/_authenticated/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'
      path: '/$number'
      fullPath: '/dashboard/organization/$organizationId/repo/$repoId/pulls/$number'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountGithubRoute: typeof LayoutAuthenticatedDashboardSettingsAccountGithubRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute:
      LayoutAuthenticatedDashboardSettingsAccountConnectionsRoute,
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountGithubRoute:
      LayoutAuthenticatedDashboardSettingsAccountGithubRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsBoardsRouteChildren {
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute
  LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsBoardsRouteChildren: LayoutAuthenticatedDashboardSettingsBoardsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsBoardsBoardIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsBoardsBoardIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute:
      LayoutAuthenticatedDashboardSettingsBoardsBoardIdVisibilityRoute,
    LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsBoardsBoardIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsBoardsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsBoardsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsOrganizationRouteChildren {
  LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute
  LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute
  LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute
  LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute
  LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute
}

const LayoutAuthenticatedDashboardSettingsOrganizationRouteChildren: LayoutAuthenticatedDashboardSettingsOrganizationRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationConnectionsRoute,
    LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationGeneralRoute,
    LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationGithubRoute,
    LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationLabelsRoute,
    LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationRolesRoute,
  }

const LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsOrganizationRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsOrganizationRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsBoardsRoute: typeof LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsConnectionsRoute: typeof LayoutAuthenticatedDashboardSettingsConnectionsRoute
  LayoutAuthenticatedDashboardSettingsOrganizationRoute: typeof LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsBoardsRoute:
      LayoutAuthenticatedDashboardSettingsBoardsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsConnectionsRoute:
      LayoutAuthenticatedDashboardSettingsConnectionsRoute,
    LayoutAuthenticatedDashboardSettingsOrganizationRoute:
      LayoutAuthenticatedDashboardSettingsOrganizationRouteWithChildren,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteChildren {
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute
}

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteChildren: LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteChildren =
  {
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesNumberRoute,
  }

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute._addFileChildren(
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteChildren,
  )

interface LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteChildren {
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute
}

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteChildren: LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteChildren =
  {
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsNumberRoute,
  }

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute._addFileChildren(
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteChildren,
  )

interface LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteChildren {
  LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteChildren: LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteChildren =
  {
    LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdMembersRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdSearchRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdIndexRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoIndexRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBacklogRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdBoardRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdGanttRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdCodeRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIssuesRouteWithChildren,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPackagesRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdPullsRouteWithChildren,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdReleasesRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdIndexRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRepoRepoIdIndexRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdBoardBoardIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteWithChildren =
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardInvitationsRoute: typeof LayoutAuthenticatedDashboardInvitationsRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute: typeof LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteWithChildren
  LayoutAuthenticatedDashboardOrganizationCreateRoute: typeof LayoutAuthenticatedDashboardOrganizationCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardInvitationsRoute:
      LayoutAuthenticatedDashboardInvitationsRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardOrganizationOrganizationIdRoute:
      LayoutAuthenticatedDashboardOrganizationOrganizationIdRouteWithChildren,
    LayoutAuthenticatedDashboardOrganizationCreateRoute:
      LayoutAuthenticatedDashboardOrganizationCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedInvitationsRoute: typeof LayoutAuthenticatedInvitationsRoute
  LayoutAuthenticatedOnboardingRoute: typeof LayoutAuthenticatedOnboardingRoute
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedInvitationsRoute: LayoutAuthenticatedInvitationsRoute,
  LayoutAuthenticatedOnboardingRoute: LayoutAuthenticatedOnboardingRoute,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  PublicBoardBoardIdRoute: PublicBoardBoardIdRoute,
  InvitationAcceptInviteIdRoute: InvitationAcceptInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
